/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/character.glb -o public/models/CharacterMap.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'typing' | 'browup' | 'angry' | 'introAnimation' | 'Blink' | 'key1' | 'key2' | 'key3' | 'key4' | 'key5' | 'key6'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    hair: THREE.Mesh
    Ear001: THREE.SkinnedMesh
    Eyebrow: THREE.SkinnedMesh
    EYEs001: THREE.SkinnedMesh
    Hand: THREE.SkinnedMesh
    Neck: THREE.SkinnedMesh
    Pant: THREE.SkinnedMesh
    Shoe: THREE.SkinnedMesh
    Sole: THREE.SkinnedMesh
    Plane007: THREE.SkinnedMesh
    BODYSHIRT: THREE.SkinnedMesh
    Cube002: THREE.Mesh
    screenlight: THREE.Mesh
    Keyboard: THREE.Mesh
    KEYS002: THREE.Mesh
    KEYS013: THREE.Mesh
    KEYS014: THREE.Mesh
    KEYS015: THREE.Mesh
    KEYS020: THREE.Mesh
    KEYS021: THREE.Mesh
    KEYS: THREE.Mesh
    KEYS001: THREE.Mesh
    KEYS003: THREE.Mesh
    KEYS004: THREE.Mesh
    KEYS005: THREE.Mesh
    KEYS006: THREE.Mesh
    KEYS007: THREE.Mesh
    KEYS008: THREE.Mesh
    KEYS009: THREE.Mesh
    KEYS010: THREE.Mesh
    KEYS011: THREE.Mesh
    KEYS012: THREE.Mesh
    KEYS016: THREE.Mesh
    KEYS017: THREE.Mesh
    KEYS018: THREE.Mesh
    KEYS019: THREE.Mesh
    KEYS022: THREE.Mesh
    KEYS023: THREE.Mesh
    KEYS024: THREE.Mesh
    KEYS025: THREE.Mesh
    KEYS026: THREE.Mesh
    KEYS027: THREE.Mesh
    KEYS028: THREE.Mesh
    KEYS029: THREE.Mesh
    KEYS030: THREE.Mesh
    KEYS031: THREE.Mesh
    KEYS032: THREE.Mesh
    KEYS033: THREE.Mesh
    KEYS034: THREE.Mesh
    KEYS035: THREE.Mesh
    KEYS036: THREE.Mesh
    KEYS037: THREE.Mesh
    KEYS038: THREE.Mesh
    KEYS039: THREE.Mesh
    Plane: THREE.Mesh
    ground: THREE.Mesh
    Plane002: THREE.Mesh
    Plane003: THREE.Mesh
    Plane017: THREE.Mesh
    Plane017_1: THREE.Mesh
    spine: THREE.Bone
  }
  materials: {
    ['Material.030']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['EyesMaterial.001']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['screenlight.001']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshPhysicalMaterial
    ['ground material.001']: THREE.MeshStandardMaterial
    ['Material.026']: THREE.MeshPhysicalMaterial
    ['Material.027']: THREE.MeshStandardMaterial
    ['Material.028']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function CharacterModel(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null!)
  const { scene, animations } = useGLTF('/models/character.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)

  React.useEffect(() => {
    // Play the typing animation by default
    if (actions && actions['typing']) {
      actions['typing'].play()
    }
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="metarig002">
          <primitive object={nodes.spine} />
          <group name="Face002" />
          <skinnedMesh name="Ear001" geometry={nodes.Ear001.geometry} material={materials['default']} skeleton={nodes.Ear001.skeleton} />
          <skinnedMesh name="Eyebrow" geometry={nodes.Eyebrow.geometry} material={materials['Material.014']} skeleton={nodes.Eyebrow.skeleton} />
          <skinnedMesh name="EYEs001" geometry={nodes.EYEs001.geometry} material={materials['EyesMaterial.001']} skeleton={nodes.EYEs001.skeleton} />
          <skinnedMesh name="Hand" geometry={nodes.Hand.geometry} material={materials['default']} skeleton={nodes.Hand.skeleton} />
          <skinnedMesh name="Neck" geometry={nodes.Neck.geometry} material={materials['default']} skeleton={nodes.Neck.skeleton} />
          <skinnedMesh name="Pant" geometry={nodes.Pant.geometry} material={materials['default']} skeleton={nodes.Pant.skeleton} />
          <skinnedMesh name="Shoe" geometry={nodes.Shoe.geometry} material={materials['default']} skeleton={nodes.Shoe.skeleton} />
          <skinnedMesh name="Sole" geometry={nodes.Sole.geometry} material={materials['default']} skeleton={nodes.Sole.skeleton} />
          <skinnedMesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials['default']} skeleton={nodes.Plane007.skeleton} morphTargetDictionary={nodes.Plane007.morphTargetDictionary} morphTargetInfluences={nodes.Plane007.morphTargetInfluences} />
          <skinnedMesh name="BODYSHIRT" geometry={nodes.BODYSHIRT.geometry} material={materials['default']} skeleton={nodes.BODYSHIRT.skeleton} morphTargetDictionary={nodes.BODYSHIRT.morphTargetDictionary} morphTargetInfluences={nodes.BODYSHIRT.morphTargetInfluences} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/character.glb')
